#  vim:ts=2:sts=2:sw=2:et
#
#  Author: KhulnaSoft, Ltd
#  Date: 2021-12-13 18:59:29 +0000 (Mon, 13 Dec 2021)
#
#  https://github.com/BuildScale/Dockerfiles
#
#  License: see accompanying KhulnaSoft, Ltd LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/company/khulnasoft
#

# https://circleci.com/docs/2.0/runner-installation-docker/

# Set up runner token:
#
#   circleci runner resource-class create <namespace>/<resource> "description" --generate-token
#
# eg.
#
#   circleci runner resource-class create buildscale/docker-runner "Docker Runner" --generate-token

# For a much more advanced setup ready to go on Kubernetes with auto-scaling, see
#
#   https://github.com/BuildScale/Kubernetes-configs

version: '2.2'

services:
  circleci:
    #image: circleci/runner:launch-agent
    # image with built-in dependencies
    image: buildscale/circleci-runner
    environment:
      CIRCLECI_API_TOKEN: $CIRCLECI_API_TOKEN     # use the token output by the 'runner resource-class create' command above
      CIRCLECI_RESOURCE_CLASS: ${CIRCLECI_RESOURCE_CLASS:-buildscale/docker-runner}  # <namespace>/<resource>
