#  vim:ts=4:sts=4:sw=4:et
#
#  Author: KhulnaSoft, Ltd
#  Date: 2019-10-01 16:14:15 +0100 (Tue, 01 Oct 2019)
#
#  https://github.com/BuildScale/Dockerfiles
#
#  License: see accompanying KhulnaSoft, Ltd LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/company/khulnasoft
#

ignored:
  # dev images build on upstream latest tag
  - DL3007
  # apk add versions need not be pinned
  - DL3018
  # fine to use curl and wget, many images have both packages due to being dev builds
  - DL4001
  #- SC1010

trustedRegistries:
  - docker.io
  #- my-company.com:5000
