#  vim:ts=2:sts=2:sw=2:et
#
#  Author: KhulnaSoft, Ltd
#  Date: 2019-03-01 17:11:46 +0000 (Fri, 01 Mar 2019)
#
#  https://github.com/BuildScale/Dockerfiles
#
#  License: see accompanying KhulnaSoft, Ltd LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/company/khulnasoft
#

version: '3'
services:
  opentsdb:
    image: buildscale/opentsdb:${VERSION:-latest}
  hbase:
    image: buildscale/hbase:${HBASE_VERSION:-latest}
  zookeeper:
    image: buildscale/zookeeper:${ZOOKEEPER_VERSION:-latest}
