#  vim:ts=2:sts=2:sw=2:et
#
#  Author: KhulnaSoft, Ltd
#  Date: 2016-12-10 09:52:03 +0000 (Sat, 10 Dec 2016)
#
#  https://github.com/BuildScale/Dockerfiles
#
#  License: see accompanying KhulnaSoft, Ltd LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/company/khulnasoft
#

version: '3'
services:
  kafka:
    image: buildscale/kafka:${VERSION:-latest}
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - ADVERTISED_HOSTNAME=$ADVERTISED_HOSTNAME
