#
#  Author: KhulnaSoft, Ltd
#  Date: 2022-01-27 18:55:16 +0000 (Thu, 27 Jan 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/BuildScale/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/company/khulnasoft
#

---
name: Docker Build CentOS Dev

on:
  push:
    branches:
      - master
      - main
    paths:
      - centos-dev/Dockerfile
      - .github/workflows/docker_build_centos_dev.yaml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  docker_build:
    name: Docker Build
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: |
      github.repository_owner == 'BuildScale' &&
      (
        github.event_name == 'schedule' ||
        (
          github.ref_type == 'branch' &&
          ( github.ref_name == github.event.repository.default_branch || github.ref_name == 'docker' )
        )
      )
    uses: BuildScale/GitHub-Actions/.github/workflows/docker_build.yaml@master
    with:
      repo_tags: |
        buildscale/centos-dev:latest
        buildscale/dev:centos
        ghcr.io/buildscale/centos-dev:latest
        ghcr.io/buildscale/dev:centos
      context: centos-dev
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
