#
#  Author: KhulnaSoft, Ltd
#  Date: 2022-05-26 12:00:50 +0100 (Thu, 26 May 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/BuildScale/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/company/khulnasoft
#

---
name: Docker Build AWS EB CLI

on:
  push:
    branches:
      - master
      - main
    paths:
      - aws-eb-cli/Dockerfile
      - .github/workflows/docker_build_aws_eb_cli.yaml
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  docker_build:
    name: Docker Build
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: |
      github.repository_owner == 'BuildScale' &&
      (
        github.event_name == 'schedule' ||
        (
          github.ref_type == 'branch' &&
          ( github.ref_name == github.event.repository.default_branch || github.ref_name == 'docker' )
        )
      )
    uses: BuildScale/GitHub-Actions/.github/workflows/docker_build.yaml@master
    with:
      repo_tags: |
        ghcr.io/buildscale/aws-eb-cli:latest
        ghcr.io/buildscale/aws-eb-cli:alpine
        buildscale/aws-eb-cli:latest
        buildscale/aws-eb-cli:alpine
      context: aws-eb-cli
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
